version: '3'

services:
  attacker-server:
    build: .
    container_name: attacker-server
    hostname: attacker-server
    tty: true           # Add this line
    stdin_open: true    # Add this line
    ports:
      - "63999:63999"
      - "63998:63998"
    volumes:
      - ./exfiltrated_data:/app/exfiltrated_data
      - ./payload:/app/payload
      - ./payload/update.sh:/app/payload/update.sh:ro
      - ./payload/dummy.sh:/app/payload/dummy.sh:ro  # Make dummy.sh accessible
    restart: unless-stopped
    networks:
      - iot_sensor-net
    # command: /bin/sh -c "apt-get update && apt-get install -y netcat-traditional && tail -f /dev/null"

networks:
  iot_sensor-net:
    external: true  # This will connect to your existing sensor network