version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    networks:
      - iot_sensor-net
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8443"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  iot_sensor-net:
    external: true  # This will connect to your existing sensor network
